[package]
name = "sls-webgpu"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]
edition = "2018"
[features]
sdl2_backend = ["sdl2"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
shaderc = "0.7"
regex = "1.5.4"

[dependencies]
raw-window-handle = "0.3.3"
nalgebra-glm = "0.3"
wgpu = "0.7.1"
log = "0.4.14"
bytemuck = { version = "1.7", features = [ "derive" ] }
lazy_static = "1.4.0"

legion = "0.4.0"

[dependencies.sdl2]
version = "0.34.4"
optional = true
features = ["default", "raw-window-handle"]