[package]
name = "sls-webgpu"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]
edition = "2018"
[features]
default = []
sdl2_backend = ["sdl2"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
#shaderc = "0.7"
regex = "1.5.4"

[dependencies]
raw-window-handle = "0.3.3"
nalgebra-glm = "0.3"
wgpu = {version= "^0.8.1", features=["trace"] }
log = "0.4.14"
bytemuck = { version = "1.7", features = [ "derive" ] }
lazy_static = "1.4.0"
downcast-rs = "1.2.0"
rand = "0.8.4"
serde ="1.0.126"
legion = "0.4.0"
serde_json = "1.0.64"
imgui-wgpu = {version= "0.15.1", features=[] }
imgui = "0.7.0"

[dependencies.sdl2]
version = "0.34.4"
optional = true
features = ["default", "raw-window-handle", "bundled"]