[workspace]

members = [
    "crates/sls-webgpu",
    "crates/game",
    "crates/sls-webgpu-html5",
    "crates/sls-webgpu-native",
    "crates/sls-webgpu-ios",
]


[profile.dev]
opt-level = 0
debug=true
[profile.dev.package."*"]
opt-level = 0
debug=true