[package]
name = 'sls-webgpu-ios'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
[dependencies.sdl2]
version = '*'
features = ['bundled']

[dependencies.sls-webgpu-game]
path = '../game'

[build_dependencies]
cbindgen = '0.20.0'
